import {
  NEGOTIATION_PROPOSAL_STATUS,
  NEGOTIATION_STATUS,
  type NegotiationProposalStatus,
  type NegotiationStatus,
} from "./constants";

export const VALID_NEGOTIATION_TRANSITIONS: Record<
  NegotiationStatus,
  readonly NegotiationStatus[]
> = {
  [NEGOTIATION_STATUS.INITIATED]: [
    NEGOTIATION_STATUS.ACTIVE,
    NEGOTIATION_STATUS.FAILED,
    NEGOTIATION_STATUS.EXPIRED,
  ],
  [NEGOTIATION_STATUS.ACTIVE]: [
    NEGOTIATION_STATUS.TERMS_PROPOSED,
    NEGOTIATION_STATUS.COUNTER_PROPOSED,
    NEGOTIATION_STATUS.FAILED,
    NEGOTIATION_STATUS.EXPIRED,
  ],
  [NEGOTIATION_STATUS.TERMS_PROPOSED]: [
    NEGOTIATION_STATUS.COUNTER_PROPOSED,
    NEGOTIATION_STATUS.TERMS_AGREED,
    NEGOTIATION_STATUS.STALLED,
    NEGOTIATION_STATUS.FAILED,
    NEGOTIATION_STATUS.EXPIRED,
  ],
  [NEGOTIATION_STATUS.COUNTER_PROPOSED]: [
    NEGOTIATION_STATUS.TERMS_PROPOSED,
    NEGOTIATION_STATUS.STALLED,
    NEGOTIATION_STATUS.FAILED,
    NEGOTIATION_STATUS.EXPIRED,
  ],
  [NEGOTIATION_STATUS.TERMS_AGREED]: [
    NEGOTIATION_STATUS.TOKEN_COLLECTED,
    NEGOTIATION_STATUS.TERMS_PROPOSED,
    NEGOTIATION_STATUS.COUNTER_PROPOSED,
    NEGOTIATION_STATUS.STALLED,
    NEGOTIATION_STATUS.FAILED,
    NEGOTIATION_STATUS.EXPIRED,
  ],
  [NEGOTIATION_STATUS.TOKEN_COLLECTED]: [
    NEGOTIATION_STATUS.DOCUMENTATION_IN_PROGRESS,
    NEGOTIATION_STATUS.STALLED,
    NEGOTIATION_STATUS.FAILED,
    NEGOTIATION_STATUS.EXPIRED,
  ],
  [NEGOTIATION_STATUS.DOCUMENTATION_IN_PROGRESS]: [
    NEGOTIATION_STATUS.READY_FOR_CLOSURE,
    NEGOTIATION_STATUS.STALLED,
    NEGOTIATION_STATUS.FAILED,
    NEGOTIATION_STATUS.EXPIRED,
  ],
  [NEGOTIATION_STATUS.READY_FOR_CLOSURE]: [
    NEGOTIATION_STATUS.DOCUMENTATION_IN_PROGRESS,
    NEGOTIATION_STATUS.CLOSED,
    NEGOTIATION_STATUS.FAILED,
    NEGOTIATION_STATUS.EXPIRED,
  ],
  [NEGOTIATION_STATUS.CLOSED]: [],
  [NEGOTIATION_STATUS.FAILED]: [],
  [NEGOTIATION_STATUS.STALLED]: [
    NEGOTIATION_STATUS.TERMS_PROPOSED,
    NEGOTIATION_STATUS.COUNTER_PROPOSED,
  ],
  [NEGOTIATION_STATUS.EXPIRED]: [],
};

// READY_FOR_CLOSURE is intentionally non-terminal so inquiry-level dedup keeps
// blocking parallel negotiations until a final terminal outcome is reached.
const TERMINAL_NEGOTIATION_STATUSES: readonly NegotiationStatus[] = [
  NEGOTIATION_STATUS.CLOSED,
  NEGOTIATION_STATUS.FAILED,
  NEGOTIATION_STATUS.EXPIRED,
];

export function validateNegotiationTransition(
  from: NegotiationStatus,
  to: NegotiationStatus,
): boolean {
  return VALID_NEGOTIATION_TRANSITIONS[from].includes(to);
}

export function isNegotiationTerminal(status: NegotiationStatus): boolean {
  return TERMINAL_NEGOTIATION_STATUSES.includes(status);
}

export const VALID_PROPOSAL_TRANSITIONS: Record<
  NegotiationProposalStatus,
  readonly NegotiationProposalStatus[]
> = {
  [NEGOTIATION_PROPOSAL_STATUS.DRAFT]: [
    NEGOTIATION_PROPOSAL_STATUS.SHARED,
    NEGOTIATION_PROPOSAL_STATUS.SUPERSEDED,
  ],
  [NEGOTIATION_PROPOSAL_STATUS.SHARED]: [
    NEGOTIATION_PROPOSAL_STATUS.BOTH_AGREED,
    NEGOTIATION_PROPOSAL_STATUS.SUPERSEDED,
  ],
  [NEGOTIATION_PROPOSAL_STATUS.BOTH_AGREED]: [],
  [NEGOTIATION_PROPOSAL_STATUS.SUPERSEDED]: [],
};

export function validateProposalTransition(
  from: NegotiationProposalStatus,
  to: NegotiationProposalStatus,
): boolean {
  return VALID_PROPOSAL_TRANSITIONS[from].includes(to);
}
