import { CHECKLIST_DEPTH, CHECKLIST_ITEM_TYPE } from "../constants";
import type { ChecklistTemplatePayload } from "./property-inspection-templates";

export const MOVE_IN_HANDOVER_TEMPLATE: ChecklistTemplatePayload = {
  name: "Move-in Handover",
  description:
    "Comprehensive move-in handover checklist for meter baselines, key inventory, appliances, and furniture condition.",
  depth: CHECKLIST_DEPTH.FULL,
  is_active: true,
  is_deleted: false,
  sections: [
    {
      section_id: "sec-meters",
      title: "Meter Readings",
      description: "Capture all utility meter baselines and supporting evidence at handover.",
      items: [
        {
          item_id: "item-meter-electricity-reading",
          label: "Electricity meter reading",
          item_type: CHECKLIST_ITEM_TYPE.NUMBER,
          is_required: true,
          requires_photo: true,
          min_depth: CHECKLIST_DEPTH.FULL,
        },
        {
          item_id: "item-meter-electricity-photo",
          label: "Electricity meter photo",
          item_type: CHECKLIST_ITEM_TYPE.PHOTO,
          is_required: true,
          requires_photo: true,
          min_depth: CHECKLIST_DEPTH.FULL,
        },
        {
          item_id: "item-meter-water-reading",
          label: "Water meter reading",
          item_type: CHECKLIST_ITEM_TYPE.NUMBER,
          is_required: true,
          requires_photo: true,
          min_depth: CHECKLIST_DEPTH.FULL,
        },
        {
          item_id: "item-meter-water-photo",
          label: "Water meter photo",
          item_type: CHECKLIST_ITEM_TYPE.PHOTO,
          is_required: true,
          requires_photo: true,
          min_depth: CHECKLIST_DEPTH.FULL,
        },
        {
          item_id: "item-meter-gas-reading",
          label: "Gas meter reading (if applicable)",
          item_type: CHECKLIST_ITEM_TYPE.NUMBER,
          is_required: false,
          requires_photo: true,
          min_depth: CHECKLIST_DEPTH.FULL,
        },
        {
          item_id: "item-meter-gas-photo",
          label: "Gas meter photo",
          item_type: CHECKLIST_ITEM_TYPE.PHOTO,
          is_required: false,
          requires_photo: true,
          min_depth: CHECKLIST_DEPTH.FULL,
        },
        {
          item_id: "item-meter-piped-gas-present",
          label: "Piped gas connection present",
          item_type: CHECKLIST_ITEM_TYPE.CHECKBOX,
          is_required: false,
          requires_photo: false,
          min_depth: CHECKLIST_DEPTH.FULL,
        },
        {
          item_id: "item-meter-dg-reading",
          label: "DG meter reading",
          item_type: CHECKLIST_ITEM_TYPE.NUMBER,
          is_required: false,
          requires_photo: false,
          min_depth: CHECKLIST_DEPTH.FULL,
        },
      ],
    },
    {
      section_id: "sec-keys",
      title: "Key Inventory",
      description: "Record exact key counts and proof of key handover.",
      items: [
        {
          item_id: "item-key-main-door-count",
          label: "Main door key count",
          item_type: CHECKLIST_ITEM_TYPE.NUMBER,
          is_required: true,
          requires_photo: false,
          min_depth: CHECKLIST_DEPTH.FULL,
        },
        {
          item_id: "item-key-bedroom-count",
          label: "Bedroom key count",
          item_type: CHECKLIST_ITEM_TYPE.NUMBER,
          is_required: true,
          requires_photo: false,
          min_depth: CHECKLIST_DEPTH.FULL,
        },
        {
          item_id: "item-key-bathroom-count",
          label: "Bathroom key count",
          item_type: CHECKLIST_ITEM_TYPE.NUMBER,
          is_required: false,
          requires_photo: false,
          min_depth: CHECKLIST_DEPTH.FULL,
        },
        {
          item_id: "item-key-letterbox-mailbox",
          label: "Letterbox/mailbox key received",
          item_type: CHECKLIST_ITEM_TYPE.CHECKBOX,
          is_required: false,
          requires_photo: false,
          min_depth: CHECKLIST_DEPTH.FULL,
        },
        {
          item_id: "item-key-parking-remote",
          label: "Parking key/remote received",
          item_type: CHECKLIST_ITEM_TYPE.CHECKBOX,
          is_required: false,
          requires_photo: false,
          min_depth: CHECKLIST_DEPTH.FULL,
        },
        {
          item_id: "item-key-access-card-count",
          label: "Gate/building access card count",
          item_type: CHECKLIST_ITEM_TYPE.NUMBER,
          is_required: false,
          requires_photo: false,
          min_depth: CHECKLIST_DEPTH.FULL,
        },
        {
          item_id: "item-key-all-keys-photo",
          label: "All keys photographed",
          item_type: CHECKLIST_ITEM_TYPE.PHOTO,
          is_required: true,
          requires_photo: true,
          min_depth: CHECKLIST_DEPTH.FULL,
        },
        {
          item_id: "item-key-spare-keys-received",
          label: "Spare keys received",
          item_type: CHECKLIST_ITEM_TYPE.CHECKBOX,
          is_required: false,
          requires_photo: false,
          min_depth: CHECKLIST_DEPTH.FULL,
        },
      ],
    },
    {
      section_id: "sec-appliances",
      title: "Appliance Condition",
      description: "Validate available appliances and utility readiness before occupancy.",
      items: [
        {
          item_id: "item-appliance-ac-condition",
          label: "AC unit(s) condition",
          item_type: CHECKLIST_ITEM_TYPE.PHOTO_CONDITION,
          is_required: true,
          requires_photo: true,
          min_depth: CHECKLIST_DEPTH.FULL,
        },
        {
          item_id: "item-appliance-geyser-condition",
          label: "Geyser/water heater condition",
          item_type: CHECKLIST_ITEM_TYPE.PHOTO_CONDITION,
          is_required: true,
          requires_photo: true,
          min_depth: CHECKLIST_DEPTH.FULL,
        },
        {
          item_id: "item-appliance-washing-machine-hookup",
          label: "Washing machine hookup present",
          item_type: CHECKLIST_ITEM_TYPE.CHECKBOX,
          is_required: false,
          requires_photo: false,
          min_depth: CHECKLIST_DEPTH.FULL,
        },
        {
          item_id: "item-appliance-chimney-condition",
          label: "Chimney/exhaust condition",
          item_type: CHECKLIST_ITEM_TYPE.CONDITION,
          is_required: false,
          requires_photo: false,
          min_depth: CHECKLIST_DEPTH.FULL,
        },
        {
          item_id: "item-appliance-fans-working-count",
          label: "Fans working count",
          item_type: CHECKLIST_ITEM_TYPE.NUMBER,
          is_required: true,
          requires_photo: false,
          min_depth: CHECKLIST_DEPTH.FULL,
        },
        {
          item_id: "item-appliance-lights-working-count",
          label: "Lights working count",
          item_type: CHECKLIST_ITEM_TYPE.NUMBER,
          is_required: true,
          requires_photo: false,
          min_depth: CHECKLIST_DEPTH.FULL,
        },
        {
          item_id: "item-appliance-inverter-condition",
          label: "Inverter/UPS condition",
          item_type: CHECKLIST_ITEM_TYPE.CONDITION,
          is_required: false,
          requires_photo: false,
          min_depth: CHECKLIST_DEPTH.FULL,
        },
        {
          item_id: "item-appliance-ro-condition",
          label: "RO water purifier condition",
          item_type: CHECKLIST_ITEM_TYPE.CONDITION,
          is_required: false,
          requires_photo: false,
          min_depth: CHECKLIST_DEPTH.FULL,
        },
        {
          item_id: "item-appliance-microwave-oven-condition",
          label: "Microwave/oven condition",
          item_type: CHECKLIST_ITEM_TYPE.CONDITION,
          is_required: false,
          requires_photo: false,
          min_depth: CHECKLIST_DEPTH.FULL,
        },
        {
          item_id: "item-appliance-overall-photos",
          label: "Overall appliance photos",
          item_type: CHECKLIST_ITEM_TYPE.PHOTO,
          is_required: true,
          requires_photo: true,
          min_depth: CHECKLIST_DEPTH.FULL,
        },
      ],
    },
    {
      section_id: "sec-furniture",
      title: "Furniture Inventory",
      description: "Capture available furniture counts and visible condition at handover.",
      items: [
        {
          item_id: "item-furniture-beds-count",
          label: "Beds count",
          item_type: CHECKLIST_ITEM_TYPE.NUMBER,
          is_required: true,
          requires_photo: false,
          min_depth: CHECKLIST_DEPTH.FULL,
        },
        {
          item_id: "item-furniture-wardrobes-count",
          label: "Wardrobes count",
          item_type: CHECKLIST_ITEM_TYPE.NUMBER,
          is_required: true,
          requires_photo: false,
          min_depth: CHECKLIST_DEPTH.FULL,
        },
        {
          item_id: "item-furniture-dining-table-chairs-count",
          label: "Dining table & chairs count",
          item_type: CHECKLIST_ITEM_TYPE.NUMBER,
          is_required: false,
          requires_photo: false,
          min_depth: CHECKLIST_DEPTH.FULL,
        },
        {
          item_id: "item-furniture-sofa-set-condition",
          label: "Sofa set condition",
          item_type: CHECKLIST_ITEM_TYPE.PHOTO_CONDITION,
          is_required: false,
          requires_photo: true,
          min_depth: CHECKLIST_DEPTH.FULL,
        },
        {
          item_id: "item-furniture-study-table-desk",
          label: "Study table/desk present",
          item_type: CHECKLIST_ITEM_TYPE.CHECKBOX,
          is_required: false,
          requires_photo: false,
          min_depth: CHECKLIST_DEPTH.FULL,
        },
        {
          item_id: "item-furniture-tv-unit",
          label: "TV unit present",
          item_type: CHECKLIST_ITEM_TYPE.CHECKBOX,
          is_required: false,
          requires_photo: false,
          min_depth: CHECKLIST_DEPTH.FULL,
        },
        {
          item_id: "item-furniture-shoe-rack",
          label: "Shoe rack present",
          item_type: CHECKLIST_ITEM_TYPE.CHECKBOX,
          is_required: false,
          requires_photo: false,
          min_depth: CHECKLIST_DEPTH.FULL,
        },
        {
          item_id: "item-furniture-curtain-rods-count",
          label: "Curtain rods count",
          item_type: CHECKLIST_ITEM_TYPE.NUMBER,
          is_required: false,
          requires_photo: false,
          min_depth: CHECKLIST_DEPTH.FULL,
        },
        {
          item_id: "item-furniture-modular-kitchen-cabinets-condition",
          label: "Modular kitchen cabinets condition",
          item_type: CHECKLIST_ITEM_TYPE.PHOTO_CONDITION,
          is_required: false,
          requires_photo: true,
          min_depth: CHECKLIST_DEPTH.FULL,
        },
        {
          item_id: "item-furniture-overall-photos",
          label: "Overall furniture photos",
          item_type: CHECKLIST_ITEM_TYPE.PHOTO,
          is_required: true,
          requires_photo: true,
          min_depth: CHECKLIST_DEPTH.FULL,
        },
      ],
    },
  ],
};
